### ISSUE TITLE
Inlay hints are not visible

### ISSUE THREAD

**Issue by sebvilhelm** [oxfist/night-owl.nvim#21]
Neovim 0.10 adds native LSP support for inlay hints, but they don't seem to work in this colorscheme:

<img width="661" alt="Screenshot 2023-11-07 at 11 36 57" src="https://github.com/oxfist/night-owl.nvim/assets/25344971/10202300-3100-42b4-9c09-595d69fbbe26">

Same lines with default colorscheme:

<img width="608" alt="Screenshot 2023-11-07 at 11 39 44" src="https://github.com/oxfist/night-owl.nvim/assets/25344971/bd68f3cd-530d-438b-8ea2-ad30dfc092b9">

**Comment by oxfist** [comment]
@sebvilhelm thanks so much for the heads up and for creating this issue. I followed VSCode's inlay hints defaults because the original Night Owl theme doesn't seem to declare colors for that:

**VSCode**
<img width="677" alt="CleanShot 2023-11-08 at 2 45 40@2x" src="https://github.com/oxfist/night-owl.nvim/assets/934679/e78ae1bf-7118-4876-8e55-729d60482c11">

**After recent commit**
<img width="703" alt="CleanShot 2023-11-08 at 2 46 50@2x" src="https://github.com/oxfist/night-owl.nvim/assets/934679/5f1a2b4d-bc36-47e1-b612-ebaa1a5abd5e">

I'm working on having setup options for this plugin in the future to customize the highlights a bit while still adhering to the original palette, so eventually I'll have the option to change these colors.

**Comment by oxfist** [comment]
@all-contributors please add @sebvilhelm for bug

**Comment by sebvilhelm** [comment]
@oxfist much appreciated, great work!
