### ISSUE TITLE
Discrepancies between VSCode and NeoVim

### ISSUE THREAD

**Issue by gheorghitahurmuz** [oxfist/night-owl.nvim#30]
Could you provide further details regarding the Treesitter and LSP configuration for this theme? I'm encountering an issue where the color palette is not being applied correctly. To illustrate this, I have attached additional screenshots showing the discrepancies between VSCode and NeoVim.

<img width="1674" alt="Screenshot 2023-11-20 at 8 13 51 PM" src="https://github.com/oxfist/night-owl.nvim/assets/12661929/79a53954-0788-4aef-911c-4c1d293e6146">

**Comment by oxfist** [comment]
Hey @gheorghitahurmuz! Did you mean to close this issue? Just to provide a brief explanation for reference to anyone, the differences you're seeing are because of two reasons:

1. My own personal decision to change the way Lua highlight groups, in particular, work. You can see in the original VSCode theme there's no much difference between variables, function calls, and properties. IMHO that goes against the purpose of the theme, and I can imagine this being a consequence of the VSCode theme no longer being supported by Sarah. 👇🏼 See screenshot below where all the arrows indicate same color being used on different semantics.
![CleanShot 2023-11-20 at 11  17 44@2x](https://github.com/oxfist/night-owl.nvim/assets/934679/d1a93b06-1050-4204-a680-9d5c95319bea)

2. On the other hand the indentation guides are very likely because of the actual character the plugin you're using has set up (maybe you use [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) like me?). If you set it to this `▏`, you'll probably have a better looking experience.

Let me know if you have any further questions! Happy to share my thought process and keep improving the theme 👍🏼
